name: gestor_del_hogar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  dio: ^5.1.2
  firebase_auth: ^4.0.0
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.6
  formz: ^0.6.0
  get_it: ^7.6.0
  go_router: ^7.1.1
  google_fonts: ^5.1.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.2
  flutter_speed_dial: ^7.0.0
  multi_dropdown: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
