// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS7Vre5k9rEe_BeYVcoy6_6V5J1qtoWuY',
    appId: '1:518856600134:web:85b699fbec487f5b3b3847',
    messagingSenderId: '518856600134',
    projectId: 'gestor-del-hogar-697f6',
    authDomain: 'gestor-del-hogar-697f6.firebaseapp.com',
    databaseURL: 'https://gestor-del-hogar-697f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestor-del-hogar-697f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGnesX8m46B68x_E4Bogzz0b6zOrm2J6s',
    appId: '1:518856600134:android:cd04f717055615f43b3847',
    messagingSenderId: '518856600134',
    projectId: 'gestor-del-hogar-697f6',
    databaseURL: 'https://gestor-del-hogar-697f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestor-del-hogar-697f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB1R5mqMnmLOQPR9lN2LGVGK691zdjtno',
    appId: '1:518856600134:ios:84265340d4c4dd6f3b3847',
    messagingSenderId: '518856600134',
    projectId: 'gestor-del-hogar-697f6',
    databaseURL: 'https://gestor-del-hogar-697f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestor-del-hogar-697f6.appspot.com',
    iosClientId: '518856600134-u88jjfrjiruvk23ghoaf7iujh5t8n63s.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestorDelHogar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB1R5mqMnmLOQPR9lN2LGVGK691zdjtno',
    appId: '1:518856600134:ios:5e7326fa7aff2c2c3b3847',
    messagingSenderId: '518856600134',
    projectId: 'gestor-del-hogar-697f6',
    databaseURL: 'https://gestor-del-hogar-697f6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gestor-del-hogar-697f6.appspot.com',
    iosClientId: '518856600134-02dh8gga8jsuhkum8is5vaaedathkf0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestorDelHogar.RunnerTests',
  );
}
